"use client";

import { useEffect, useState } from "react";
import { Download, FileCheck2, LoaderCircle } from "lucide-react";
import type { EvidenceResult } from "@/types/forensics";
import { dfirApi } from "@/services/api";
import { DashboardShell } from "@/components/layout/DashboardShell";

import { motion } from "framer-motion";

export function CertificateWorkspace() {
  const [caseData, setCaseData] = useState<EvidenceResult | null>(null); const [preview, setPreview] = useState(false);
  useEffect(() => { const raw = sessionStorage.getItem("pratikriya-active-case"); if (raw) try { setCaseData(JSON.parse(raw)); } catch { /* unavailable case is handled below */ } }, []);
  const pdfUrl = caseData ? dfirApi.certificateUrl(caseData.ingestion.hash_sha256) : null;
  return <DashboardShell title="Certificate generator" certificate><motion.div initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} className="certificate-page"><div className="certificate-toolbar"><div><p className="eyebrow">Section 63(4) BSA workspace</p><h2>Official evidence certificate</h2><p>Generated by the backend from the active evidence record. Examiner countersignature remains required.</p></div>{caseData && <div className="certificate-actions"><button className="btn-primary" onClick={() => setPreview(true)}><FileCheck2 size={17} /> Generate preview</button><a className="btn-secondary" href={pdfUrl ?? "#"} download><Download size={17} /> Download PDF</a></div>}</div>{!caseData ? <div className="certificate-empty panel"><FileCheck2 size={36} /><h3>No active evidence record</h3><p>Upload and process evidence in the dashboard before generating its backend-authoritative certificate.</p></div> : preview ? <section className="document-preview"><div className="paper-header"><span className="devanagari">प्रतिक्रिया</span><b>PRATIKRIYA / LEGAL OUTPUT</b><small className="mono">CASE {caseData.ingestion.hash_sha256.slice(0, 16)}…</small></div><object data={pdfUrl ?? undefined} type="application/pdf" aria-label="Backend generated evidence certificate"><div className="pdf-loading"><LoaderCircle className="spin" />Loading backend PDF preview…</div></object><p className="pdf-note">This document is a Section 63(4)(c)-compliant certificate template — pending examiner countersignature.</p></section> : <section className="certificate-empty panel"><FileCheck2 size={36} /><h3>Ready to generate</h3><p>Review the active evidence hash, then generate the official PDF preview directly from the backend.</p><code>{caseData.ingestion.hash_sha256}</code></section>}</motion.div></DashboardShell>;
}
